package menu.view;

import global.controller.GlobalControlCodes;
import global.view.View;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Observable;

public class MenuView implements View {
    private JFrame frame;
    private JPanel panel;
    private JButton buttonShare;
    private JButton buttonTrade;
    private JButton buttonLogoff;
    private JButton buttonBroker;

    public MenuView() {
        frame = new JFrame("MenuView");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.pack();
    }

    public void showView() {
        frame.setVisible(true);
    }

    @Override
    public void closeView() {
        frame.dispose();
    }

    public void setActionListeners(ActionListener actionListener) {
        setLogoffButtonListener(actionListener);
        setShareButtonListener(actionListener);
        setTradeButtonListener(actionListener);
    }

    private void setLogoffButtonListener(ActionListener actionListener) {
        System.out.println("MenuView: adding logoff listener");
        buttonLogoff.addActionListener(actionListener);
        buttonLogoff.setActionCommand(GlobalControlCodes.LOG_OFF.name());
    }

    private void setShareButtonListener(ActionListener actionListener) {
        System.out.println("MenuView: adding share listener");
        buttonShare.addActionListener(actionListener);
        buttonShare.setActionCommand(GlobalControlCodes.SHARE.name());
    }

    private void setTradeButtonListener(ActionListener actionListener) {
        System.out.println("MenuView: adding trade listener");
        buttonTrade.addActionListener(actionListener);
        buttonTrade.setActionCommand(GlobalControlCodes.TRADE_OPEN.name());
    }

    private void setBrokerButtonListener(ActionListener actionListener) {
        System.out.println("MenuView: adding broker listener");
        buttonBroker.addActionListener(actionListener);
        buttonBroker.setActionCommand(GlobalControlCodes.BROKER_OPEN.name());
    }

    public void update(Observable o, Object arg) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        buttonShare = new JButton();
        buttonShare.setText("Shares");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(buttonShare, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel.add(spacer3, gbc);
        buttonTrade = new JButton();
        buttonTrade.setText("Trades");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(buttonTrade, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(spacer4, gbc);
        buttonLogoff = new JButton();
        buttonLogoff.setText("Log Off");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(buttonLogoff, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(spacer7, gbc);
        buttonBroker = new JButton();
        buttonBroker.setText("Brokers");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(buttonBroker, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(spacer8, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
