package global.controller;

public enum GlobalControlCodes {
    NO_SUCH_USER,
    INVALID_CREDENTIAL,
    USER_EXISTS,
    REGISTERED,
    LOG_IN,
    LOG_OFF,
    FAILED,
    SHARE_OPEN,
    SHARE_CLOSE,
    TRACK_OPEN,
    TRACK_CLOSE,
    TRACK_SHARE,
    TRADE_OPEN,
    TRADE_CLOSE,
    TRADE_SEARCH,
    BROKER_OPEN,
    BROKER_CLOSE,
    BROKER_TRADE,
    SHAREHOLDER_OPEN,
    SHAREHOLDER_CLOSE,
    SHAREHOLDER_TRADE,
    EXIT
}
