package share.view;

import javax.swing.*;
import javax.swing.table.TableModel;
import java.awt.*;
import java.util.Arrays;
import java.util.Observable;
import java.util.Observer;
import java.util.Vector;

public class ShareView implements Observer {
    private JPanel panel;
    private JTable table;
    private JPanel panelTable;
    private JButton button1;
    private JButton button2;
    private JPanel panelButton;
    private JScrollPane panelScroll;

    private String[] columnNames = {
            "Share ID",
            "Trade Code",
            "Company Name",
            "Share Price",
            "Share Value",
            "Share Quantity"};


    public ShareView() {
        JFrame frame = new JFrame("ShareView");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void populateTable(Vector data) {
        TableModel tableModel = new global.TableModel(data, new Vector<>(Arrays.asList(columnNames)));
        table.setModel(tableModel);

    }

    @Override
    public void update(Observable o, Object arg) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        panelTable = new JPanel();
        panelTable.setLayout(new BorderLayout(0, 0));
        panel.add(panelTable, BorderLayout.CENTER);
        panelScroll = new JScrollPane();
        panelScroll.setHorizontalScrollBarPolicy(31);
        panelScroll.setVerticalScrollBarPolicy(22);
        panelTable.add(panelScroll, BorderLayout.CENTER);
        table = new JTable();
        table.setPreferredScrollableViewportSize(new Dimension(450, 250));
        table.setShowVerticalLines(true);
        panelScroll.setViewportView(table);
        panelButton = new JPanel();
        panelButton.setLayout(new GridBagLayout());
        panel.add(panelButton, BorderLayout.SOUTH);
        button1 = new JButton();
        button1.setText("Button");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelButton.add(button1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelButton.add(spacer1, gbc);
        button2 = new JButton();
        button2.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelButton.add(button2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
