package view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import control.LoginControl;

import javax.swing.*;
import java.awt.*;
import java.util.Observable;
import java.util.Observer;

public class LoginForm implements Observer {
    private JTextField fieldName;
    private JPasswordField fieldPassword;
    private JButton buttonLogin;
    private JLabel labelName;
    private JLabel labelPassword;
    private JPanel panel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public LoginForm() {
        JFrame frame = new JFrame("LoginForm");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void setLoginControl(LoginControl loginControl) {
        System.out.println("LoginView: adding controller");
        loginControl = loginControl;
        buttonLogin.addActionListener(loginControl);
    }

    public String getUserPassword() {
        return String.valueOf(fieldPassword.getPassword());
    }

    public String getUserName() {
        return fieldName.getText();
    }

    @Override
    public void update(Observable o, Object arg) {
        System.out.println("View: " + (boolean) arg);
        if (!(boolean) arg) {
            showedFailedMessageDialog();
        }

    }

    private void showedFailedMessageDialog() {
        JOptionPane.showMessageDialog(null
                , "Invalid user credential", "Log In"
                , JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        labelName = new JLabel();
        labelName.setText("User Name");
        panel.add(labelName, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldName = new JTextField();
        panel.add(fieldName, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelPassword = new JLabel();
        labelPassword.setText("Password");
        panel.add(labelPassword, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldPassword = new JPasswordField();
        panel.add(fieldPassword, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        buttonLogin = new JButton();
        buttonLogin.setText("Log In");
        panel.add(buttonLogin, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
