package global;

public enum GlobalControlCodes {
    LOG_IN,
    LOG_OFF,
    SHARE_OPEN,
    SHARE_CLOSE,
    TRACK_OPEN,
    TRACK_CLOSE,
    TRACK_SHARE,
    TRADE_OPEN,
    TRADE_CLOSE,
    TRADE_SEARCH,
    BROKER_OPEN,
    BROKER_CLOSE,
    BROKER_HISTORY,
    SHAREHOLDER_OPEN,
    SHAREHOLDER_CLOSE,
    SHAREHOLDER_HISTORY,
    EXIT
}
